export const ADD_SERVICE = 'ADD_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const SET_EDIT_SERVICE_FIELD = 'SET_EDIT_SERVICE_FIELD';
export const RESET_EDIT_SERVICE_FIELD = 'RESET_EDIT_SERVICE_FIELD';
export const RESET_SERVICE_FIELD = 'RESET_SERVICE_FIELD';
export const CHANGE_FILTER_FIELD = 'CHANGE_FILTER_FIELD';
